### ISSUE TITLE
Valid config file could not be found when config transform files are present

### ISSUE THREAD

**Issue by chrisdevita** [mthamil/EFDocumentationGenerator#12] opened 2017-07-11 21:41 UTC
For web applications a valid config file could not be found.  After a bit of investigating I found that this happens when there are config transform files associated with the Web.config file (Web.Debug.config and Web.Release.config).

**Comment by mthamil** [comment] 2017-07-13 14:24
Thanks for the report. Just out of curiosity, which config is your connection string information in? Or is it in multiple?

**Comment by chrisdevita** [comment] 2017-07-13 15:54
Its in web.config. I was just testing using the default web application project template that visual studio provides. When I deleted the extra config files the document generator worked.

**Comment by chrisdevita** [comment] 2017-07-13 15:55
Its in web.config. I was just testing using the default web application project template that visual studio provides. When I deleted the extra config files the document generator worked.

**Comment by mthamil** [comment] 2017-07-13 15:59
Alright, thanks. It may be a regression because I thought at one point it worked.

**Comment by mthamil** [comment] 2017-10-16 04:03
This is fixed in [v2.1.1](https://github.com/mthamil/EFDocumentationGenerator/releases/tag/v2.1.1).

**Closed by mthamil** 2017-10-16 04:03 UTC
